# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [6]:
print(np.__version__)
np.show_config()

2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.30
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/opt/miniconda3/conda-bld/numpy_and_

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [10]:
a = np.random.random((2, 3, 5))
print(a)


[[[0.59813449 0.28904394 0.39482242 0.36280547 0.56319081]
  [0.28949674 0.78950932 0.52376215 0.24669149 0.461252  ]
  [0.63249561 0.1917463  0.41929122 0.18639135 0.19008516]]

 [[0.70268177 0.83544583 0.78347816 0.2792954  0.8136634 ]
  [0.73607388 0.05747577 0.70204341 0.59173997 0.16662254]
  [0.33883435 0.74202185 0.36444553 0.02893348 0.14022855]]]



### 4. Print a.


In [11]:
print(a)

[[[0.59813449 0.28904394 0.39482242 0.36280547 0.56319081]
  [0.28949674 0.78950932 0.52376215 0.24669149 0.461252  ]
  [0.63249561 0.1917463  0.41929122 0.18639135 0.19008516]]

 [[0.70268177 0.83544583 0.78347816 0.2792954  0.8136634 ]
  [0.73607388 0.05747577 0.70204341 0.59173997 0.16662254]
  [0.33883435 0.74202185 0.36444553 0.02893348 0.14022855]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [12]:
b = np.random.random((5, 2, 3))


### 6. Print b.


In [13]:
print(b)

[[[0.41088988 0.06978335 0.19028052]
  [0.70556683 0.6911826  0.19501871]]

 [[0.95288664 0.78371172 0.62151962]
  [0.35902784 0.43798006 0.38472506]]

 [[0.41612577 0.28461349 0.5774641 ]
  [0.81703673 0.4417534  0.7179977 ]]

 [[0.67352686 0.27232752 0.94505942]
  [0.76500462 0.4009383  0.62462608]]

 [[0.34765708 0.62526738 0.9387451 ]
  [0.61518149 0.99439545 0.52478428]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [19]:
print(a.size == b.size)



True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
c = a + b
print(c)
#we need exactly equal or one of the dimensions must be 1.

AttributeError: module 'numpy' has no attribute 'a'



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [22]:
c = b.transpose(1, 2, 0)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [24]:
d = c + a
print(d)

[[[1.00902437 1.24193058 0.81094819 1.03633233 0.91084789]
  [0.35928009 1.57322104 0.80837564 0.519019   1.08651938]
  [0.82277612 0.81326592 0.99675532 1.13145077 1.12883026]]

 [[1.4082486  1.19447367 1.60051489 1.04430002 1.42884489]
  [1.42725648 0.49545583 1.14379681 0.99267827 1.16101798]
  [0.53385306 1.12674691 1.08244323 0.65355956 0.66501283]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a)
print(d)
# They maintain the same structure but with different values.


[[[0.59813449 0.28904394 0.39482242 0.36280547 0.56319081]
  [0.28949674 0.78950932 0.52376215 0.24669149 0.461252  ]
  [0.63249561 0.1917463  0.41929122 0.18639135 0.19008516]]

 [[0.70268177 0.83544583 0.78347816 0.2792954  0.8136634 ]
  [0.73607388 0.05747577 0.70204341 0.59173997 0.16662254]
  [0.33883435 0.74202185 0.36444553 0.02893348 0.14022855]]]
[[[1.00902437 1.24193058 0.81094819 1.03633233 0.91084789]
  [0.35928009 1.57322104 0.80837564 0.519019   1.08651938]
  [0.82277612 0.81326592 0.99675532 1.13145077 1.12883026]]

 [[1.4082486  1.19447367 1.60051489 1.04430002 1.42884489]
  [1.42725648 0.49545583 1.14379681 0.99267827 1.16101798]
  [0.53385306 1.12674691 1.08244323 0.65355956 0.66501283]]]



### 12. Multiply a and c. Assign the result to e.


In [27]:
e = a * c



### 13. Does e equal to a? Why or why not?


In [ ]:
print(e == a)
#because b have a random values, and the conversion only put the same order but no the same values


[[[False False False False False]
  [False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]
  [False False False False False]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [30]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.600514889867351
0.3592800862429959
1.0068926644910559



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [31]:
f = np.empty_like(d)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [33]:
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_min)] = 0
f[(d == d_max)] = 100






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [34]:
print(d)
print(f)

[[[1.00902437 1.24193058 0.81094819 1.03633233 0.91084789]
  [0.35928009 1.57322104 0.80837564 0.519019   1.08651938]
  [0.82277612 0.81326592 0.99675532 1.13145077 1.12883026]]

 [[1.4082486  1.19447367 1.60051489 1.04430002 1.42884489]
  [1.42725648 0.49545583 1.14379681 0.99267827 1.16101798]
  [0.53385306 1.12674691 1.08244323 0.65355956 0.66501283]]]
[[[ 75.  75.  25.  75.  25.]
  [  0.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  75.]]

 [[ 75.  75. 100.  75.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  75.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [38]:
e = np.empty_like(f, dtype=str)
e[(d > d_min) & (d < d_mean)] = 'A'
e[(d > d_mean) & (d < d_max)] = 'B'
e[(d == d_mean)] = 'C'
e[(d == d_min)] = 'D'
e[(d == d_max)] = 'E'

print(e)

[[['B' 'B' 'A' 'B' 'A']
  ['D' 'B' 'A' 'A' 'B']
  ['A' 'A' 'A' 'B' 'B']]

 [['B' 'B' 'E' 'B' 'B']
  ['B' 'A' 'B' 'A' 'B']
  ['A' 'B' 'B' 'A' 'A']]]
